#!/usr/bin/env tsx
// Generates the idempotent SQLite bootstrap schema consumed at Kimaki startup.

import fs from 'node:fs'
import path from 'node:path'
import { execAsync } from '../src/exec-async.js'

const root = process.cwd()
const outputPath = path.join(root, 'src/schema.sql')

function makeSchemaIdempotent(sql: string) {
  return sql
    .split('\n')
    .map((line) => {
      return line
        .replace(/^CREATE TABLE\b(?! IF NOT EXISTS)/i, 'CREATE TABLE IF NOT EXISTS')
        .replace(/^CREATE UNIQUE INDEX\b(?! IF NOT EXISTS)/i, 'CREATE UNIQUE INDEX IF NOT EXISTS')
        .replace(/^CREATE INDEX\b(?! IF NOT EXISTS)/i, 'CREATE INDEX IF NOT EXISTS')
    })
    .filter((line) => !/^CREATE TABLE IF NOT EXISTS [`"]?sqlite_sequence[`"]?/i.test(line.trim()))
    .join('\n')
}

async function main() {
  console.log('Exporting Drizzle schema SQL...')
  const result = await execAsync('pnpm drizzle-kit export', { cwd: root })
  const rawSql = result.stdout.trim()
  const firstSqlLine = rawSql.split('\n').find((line) => line.trim() !== '')
  if (!firstSqlLine || !/^CREATE\s+(TABLE|INDEX|UNIQUE\s+INDEX)\b/i.test(firstSqlLine)) {
    throw new Error('drizzle-kit export did not print SQL to stdout')
  }

  console.log(`Writing ${outputPath}...`)
  const sql = [
    '-- This file is generated by pnpm generate:sql. Do not edit manually.',
    makeSchemaIdempotent(rawSql),
    '',
  ].join('\n')
  fs.writeFileSync(outputPath, sql)
  console.log('Schema SQL generated.')
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack : String(error))
  process.exit(1)
})
