-- This file is generated by pnpm generate:sql. Do not edit manually.
CREATE TABLE IF NOT EXISTS `bot_api_keys` (
	`app_id` text PRIMARY KEY,
	`gemini_api_key` text,
	`openai_api_key` text,
	`xai_api_key` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_bot_api_keys_app_id_bot_tokens_app_id_fk` FOREIGN KEY (`app_id`) REFERENCES `bot_tokens`(`app_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `bot_tokens` (
	`app_id` text PRIMARY KEY,
	`token` text NOT NULL,
	`bot_mode` text DEFAULT 'self_hosted' NOT NULL,
	`client_id` text,
	`client_secret` text,
	`proxy_url` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`last_used_at` datetime
);

CREATE TABLE IF NOT EXISTS `channel_agents` (
	`channel_id` text PRIMARY KEY,
	`agent_name` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_agents_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_directories` (
	`channel_id` text PRIMARY KEY,
	`directory` text NOT NULL,
	`channel_type` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `channel_mention_mode` (
	`channel_id` text PRIMARY KEY,
	`enabled` integer DEFAULT 0 NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_mention_mode_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_models` (
	`channel_id` text PRIMARY KEY,
	`model_id` text NOT NULL,
	`variant` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_models_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_verbosity` (
	`channel_id` text PRIMARY KEY,
	`verbosity` text DEFAULT 'tools_and_text' NOT NULL,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_verbosity_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_worktrees` (
	`channel_id` text PRIMARY KEY,
	`enabled` integer DEFAULT 0 NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_worktrees_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `forum_sync_configs` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`app_id` text NOT NULL,
	`forum_channel_id` text NOT NULL,
	`output_dir` text NOT NULL,
	`direction` text DEFAULT 'bidirectional' NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_forum_sync_configs_app_id_bot_tokens_app_id_fk` FOREIGN KEY (`app_id`) REFERENCES `bot_tokens`(`app_id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `global_models` (
	`app_id` text PRIMARY KEY,
	`model_id` text NOT NULL,
	`variant` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_global_models_app_id_bot_tokens_app_id_fk` FOREIGN KEY (`app_id`) REFERENCES `bot_tokens`(`app_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `ipc_requests` (
	`id` text PRIMARY KEY,
	`type` text NOT NULL,
	`session_id` text NOT NULL,
	`thread_id` text NOT NULL,
	`payload` text NOT NULL,
	`response` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT `fk_ipc_requests_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `part_messages` (
	`part_id` text PRIMARY KEY,
	`message_id` text NOT NULL,
	`thread_id` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_part_messages_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `scheduled_tasks` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`status` text DEFAULT 'planned' NOT NULL,
	`schedule_kind` text NOT NULL,
	`run_at` datetime,
	`cron_expr` text,
	`timezone` text,
	`next_run_at` datetime NOT NULL,
	`running_started_at` datetime,
	`last_run_at` datetime,
	`last_error` text,
	`attempts` integer DEFAULT 0 NOT NULL,
	`payload_json` text NOT NULL,
	`prompt_preview` text NOT NULL,
	`channel_id` text,
	`thread_id` text,
	`session_id` text,
	`project_directory` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_scheduled_tasks_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT `fk_scheduled_tasks_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `session_agents` (
	`session_id` text PRIMARY KEY,
	`agent_name` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `session_events` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`session_id` text NOT NULL,
	`thread_id` text NOT NULL,
	`timestamp` integer NOT NULL,
	`event_index` integer NOT NULL,
	`event_json` text NOT NULL,
	CONSTRAINT `fk_session_events_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `session_models` (
	`session_id` text PRIMARY KEY,
	`model_id` text NOT NULL,
	`variant` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `session_start_sources` (
	`session_id` text PRIMARY KEY,
	`schedule_kind` text NOT NULL,
	`scheduled_task_id` integer,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_session_start_sources_scheduled_task_id_scheduled_tasks_id_fk` FOREIGN KEY (`scheduled_task_id`) REFERENCES `scheduled_tasks`(`id`) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `thread_sessions` (
	`thread_id` text PRIMARY KEY,
	`session_id` text NOT NULL,
	`source` text DEFAULT 'kimaki' NOT NULL,
	`last_synced_name` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `thread_worktrees` (
	`thread_id` text PRIMARY KEY,
	`worktree_name` text NOT NULL,
	`worktree_directory` text,
	`project_directory` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`error_message` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_thread_worktrees_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS `forum_sync_configs_app_id_forum_channel_id_key` ON `forum_sync_configs` (`app_id`,`forum_channel_id`);
CREATE INDEX IF NOT EXISTS `ipc_requests_status_created_at_idx` ON `ipc_requests` (`status`,`created_at`);
CREATE INDEX IF NOT EXISTS `scheduled_tasks_status_next_run_at_idx` ON `scheduled_tasks` (`status`,`next_run_at`);
CREATE INDEX IF NOT EXISTS `scheduled_tasks_channel_id_status_idx` ON `scheduled_tasks` (`channel_id`,`status`);
CREATE INDEX IF NOT EXISTS `scheduled_tasks_thread_id_status_idx` ON `scheduled_tasks` (`thread_id`,`status`);
CREATE INDEX IF NOT EXISTS `session_events_session_id_timestamp_event_index_id_idx` ON `session_events` (`session_id`,`timestamp`,`event_index`,`id`);
CREATE INDEX IF NOT EXISTS `session_events_thread_id_timestamp_event_index_id_idx` ON `session_events` (`thread_id`,`timestamp`,`event_index`,`id`);
CREATE INDEX IF NOT EXISTS `session_start_sources_scheduled_task_id_idx` ON `session_start_sources` (`scheduled_task_id`);
